name: Release Workflow

on:
  release:
    types: [published]

env:
  TAG_NAME: ${{ github.event.release.tag_name }}

jobs:
  dockerhub-build-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get major version num and update tag
        run: |
          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "MAJOR=${TAG_NAME%%.*}" >> $GITHUB_ENV
      -  
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push major version
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.MAJOR }}
      -
        name: Build and push this version
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.VERSION }}
      -
        name: Build and push latest version
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:latest
